[package]
name = "rusty_json"
version = "0.1.0"
authors = ["SimonMaracine <simonmaracine@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
